version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbpruebanet
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  pruebaapp:
    build: .
    container_name: pruebaapp_container
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=dbpruebanet;user=user;password=userpassword"
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
